--- 
name: lb-mon-gts-9-24-2019
namespace: com.citrix.adc.stylebooks
version: "1.0"
description: "This stylebook defines a typical Load Balanced Application configuration with monitors."
display-name: "HTTP/SSL LoadBalancing (with Monitors) StyleBook"
private: true
schema-version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"
  - 
    namespace: com.citrix.adc.stylebooks
    prefix: stlb
    version: "1.0"
  - 
    namespace: com.citrix.adc.commontypes
    prefix: cmtypes
    version: "1.0"
parameters-default-sources:
  - stlb::lb-gts-9-24-2019
parameters:
  -
    name: monitor-list
    label: "Monitors to be used"
    required: true 
    type: object
    parameters:  
      - 
        name: tcp-mon
        label: "TCP Monitor"
        description: "Use TCP Monitor to check port availability on backend server"
        type: boolean
        required: true
      -
        name: ping-mon
        label: "Ping Monitor"
        description: "Use PING Monitor to check ICMP reachability of backend server"
        type: boolean
        required: true
      -
        name: adv-mon
        label: "Advanced Monitor"
        type: object
        parameters: 
          -
            name: monitors
            label: "List of Monitors"
            description: "List of Monitors to monitor Application Servers"
            type: cmtypes::monitor[]
substitutions:
  mon-name(appname, monname): $appname + "-" + $parameters.request-id + "-mon-" + $monname
components: 
  - 
    name: lb-comp
    type: stlb::lb-gts-9-24-2019 
    properties-default-sources:
      - $parameters
  -
    name: tcp-monitor-svcg-binding-comp
    condition:  $parameters.monitor-list.tcp-mon
    type: ns::servicegroup_lbmonitor_binding
    properties:
      servicegroupname: $components.lb-comp.outputs.servicegroup.properties.servicegroupname
      monitor_name: tcp
  -
    name: ping-monitor-svcg-binding-comp
    condition:  $parameters.monitor-list.ping-mon
    type: ns::servicegroup_lbmonitor_binding
    properties:
      servicegroupname: $components.lb-comp.outputs.servicegroup.properties.servicegroupname
      monitor_name: ping
  -
    name: monitors-comp
    type: cmtypes::monitor-gts-9-24-2019
    condition: $parameters.monitor-list.adv-mon.monitors
    repeat: $parameters.monitor-list.adv-mon.monitors
    repeat-item: mon
    repeat-index: ndx
    description: "Builds a list of Citrix ADC monitor objects and binds them to the servicegroup of this LB config"
    properties-default-sources:
      - $mon
    properties:
        monitorname: $substitutions.mon-name($parameters.lb-appname, $mon.monitorname)
        netprofile: $components.lb-comp.outputs.netprofile.properties.name
    components:
      -
        name: monitor-svcg-binding-comp
        condition:  $parameters.svc-servers
        type: ns::servicegroup_lbmonitor_binding
        properties:
          servicegroupname: $components.lb-comp.outputs.servicegroup.properties.servicegroupname
          monitor_name: $parent.properties.monitorname
outputs: 
  - 
    name: lbvserver
    value: $components.lb-comp.outputs.lbvserver
  - 
    name: servicegroup
    condition:  $parameters.svc-servers
    value: $components.lb-comp.outputs.servicegroup
  - 
    name: monitors
    value: $components.monitors-comp
